<a href="https://colab.research.google.com/github/asifisa/customer_conversion_prediction/blob/main/CustomerConversionPrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import sklearn as sns
import matplotlib.pyplot as plt


In [ ]:
data=pd.read_csv("/content/train.csv")

In [ ]:
data

age           job   marital education_qual  call_type  day  mon   dur  \
0       58    management   married       tertiary    unknown    5  may   261   
1       44    technician    single      secondary    unknown    5  may   151   
2       33  entrepreneur   married      secondary    unknown    5  may    76   
3       47   blue-collar   married        unknown    unknown    5  may    92   
4       33       unknown    single        unknown    unknown    5  may   198   
...    ...           ...       ...            ...        ...  ...  ...   ...   
45206   51    technician   married       tertiary   cellular   17  nov   977   
45207   71       retired  divorced        primary   cellular   17  nov   456   
45208   72       retired   married      secondary   cellular   17  nov  1127   
45209   57   blue-collar   married      secondary  telephone   17  nov   508   
45210   37  entrepreneur   married      secondary   cellular   17  nov   361   

       num_calls prev_outcome    y  
0              1      unknown   no  
1              1      unknown   no  
2              1      unknown   no  
3              1      unknown   no  
4              1      unknown   no  
...          ...          ...  ...  
45206          3      unknown  yes  
45207          2      unknown  yes  
45208          5      success  yes  
45209          4      unknown   no  
45210          2        other   no  

[45211 rows x 11 columns]

In [ ]:
data.isnull().sum()

age               0
job               0
marital           0
education_qual    0
call_type         0
day               0
mon               0
dur               0
num_calls         0
prev_outcome      0
y                 0
dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             45211 non-null  int64 
 1   job             45211 non-null  object
 2   marital         45211 non-null  object
 3   education_qual  45211 non-null  object
 4   call_type       45211 non-null  object
 5   day             45211 non-null  int64 
 6   mon             45211 non-null  object
 7   dur             45211 non-null  int64 
 8   num_calls       45211 non-null  int64 
 9   prev_outcome    45211 non-null  object
 10  y               45211 non-null  object
dtypes: int64(4), object(7)
memory usage: 3.8+ MB


In [ ]:
data.describe()

age           day           dur     num_calls
count  45211.000000  45211.000000  45211.000000  45211.000000
mean      40.936210     15.806419    258.163080      2.763841
std       10.618762      8.322476    257.527812      3.098021
min       18.000000      1.000000      0.000000      1.000000
25%       33.000000      8.000000    103.000000      1.000000
50%       39.000000     16.000000    180.000000      2.000000
75%       48.000000     21.000000    319.000000      3.000000
max       95.000000     31.000000   4918.000000     63.000000

In [ ]:
data.columns

Index(['age', 'job', 'marital', 'education_qual', 'call_type', 'day', 'mon',
       'dur', 'num_calls', 'prev_outcome', 'y'],
      dtype='object')

In [ ]:
data.marital.unique()

array(['married', 'single', 'divorced'], dtype=object)

In [ ]:
data.age.unique()

array([58, 44, 33, 47, 35, 28, 42, 43, 41, 29, 53, 57, 51, 45, 60, 56, 32,
       25, 40, 39, 52, 46, 36, 49, 59, 37, 50, 54, 55, 48, 24, 38, 31, 30,
       27, 34, 23, 26, 61, 22, 21, 20, 66, 62, 83, 75, 67, 70, 65, 68, 64,
       69, 72, 71, 19, 76, 85, 63, 90, 82, 73, 74, 78, 80, 94, 79, 77, 86,
       95, 81, 18, 89, 84, 87, 92, 93, 88])

In [ ]:
data.job.unique()

array(['management', 'technician', 'entrepreneur', 'blue-collar',
       'unknown', 'retired', 'admin.', 'services', 'self-employed',
       'unemployed', 'housemaid', 'student'], dtype=object)

In [ ]:
data.education_qual.unique()

array(['tertiary', 'secondary', 'unknown', 'primary'], dtype=object)

In [ ]:
data.call_type.unique()

array(['unknown', 'cellular', 'telephone'], dtype=object)

In [ ]:
data.dur.unique()

array([ 261,  151,   76, ..., 1298, 1246, 1556])

In [ ]:
pd.unique(data[['dur']].values.ravel('k'))

array([ 261,  151,   76, ..., 1298, 1246, 1556])

In [ ]:
X=data.iloc[:,:-1]
y=data.iloc[:,-1]

In [ ]:
y

0         no
1         no
2         no
3         no
4         no
        ... 
45206    yes
45207    yes
45208    yes
45209     no
45210     no
Name: y, Length: 45211, dtype: object

In [ ]:
X

age           job   marital education_qual  call_type  day  mon   dur  \
0       58    management   married       tertiary    unknown    5  may   261   
1       44    technician    single      secondary    unknown    5  may   151   
2       33  entrepreneur   married      secondary    unknown    5  may    76   
3       47   blue-collar   married        unknown    unknown    5  may    92   
4       33       unknown    single        unknown    unknown    5  may   198   
...    ...           ...       ...            ...        ...  ...  ...   ...   
45206   51    technician   married       tertiary   cellular   17  nov   977   
45207   71       retired  divorced        primary   cellular   17  nov   456   
45208   72       retired   married      secondary   cellular   17  nov  1127   
45209   57   blue-collar   married      secondary  telephone   17  nov   508   
45210   37  entrepreneur   married      secondary   cellular   17  nov   361   

       num_calls prev_outcome  
0              1      unknown  
1              1      unknown  
2              1      unknown  
3              1      unknown  
4              1      unknown  
...          ...          ...  
45206          3      unknown  
45207          2      unknown  
45208          5      success  
45209          4      unknown  
45210          2        other  

[45211 rows x 10 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
X_train

age          job   marital education_qual call_type  day  mon  dur  \
13932   57       admin.  divorced      secondary  cellular   10  jul  724   
9894    37      unknown   married        unknown   unknown    9  jun   63   
39946   35   technician  divorced      secondary  cellular    2  jun  102   
9217    35       admin.   married      secondary   unknown    5  jun  247   
4124    38     services    single       tertiary   unknown   19  may  138   
...    ...          ...       ...            ...       ...  ...  ...  ...   
30403   35   management    single       tertiary  cellular    5  feb   39   
21243   35   management   married       tertiary  cellular   18  aug  233   
42613   35   management   married       tertiary  cellular   11  jan  261   
43567   70      retired   married      secondary  cellular   27  apr  149   
2732    46  blue-collar    single      secondary   unknown   14  may  194   

       num_calls prev_outcome  
13932          1      unknown  
9894           1      unknown  
39946          4      failure  
9217           1      unknown  
4124           1      unknown  
...          ...          ...  
30403          1      unknown  
21243         12      unknown  
42613          2      unknown  
43567          2      failure  
2732           4      unknown  

[36168 rows x 10 columns]